### ISSUE TITLE
可以给一个测试bag包吗？

### ISSUE THREAD

**Issue by JokerJohn** [lzyplayer/localization_robot_infantry#1]
可以给一个测试bag包吗？谢谢

**Comment by lzyplayer** [comment]
- 任何带有激光点云话题的数据包和一张对应的地图都可以被用来测试这个系统
- example：
  - ndt_omp项目作者在koide3中hdl_localization所提供的数据：
  - 地图：（存放于/data）
    - https://github.com/koide3/hdl_localization/raw/master/data/map.pcd
  -  数据包：
     -  [hdl_400.bag.tar.gz](http://www.aisl.cs.tut.ac.jp/databases/hdl_graph_slam/hdl_400.bag.tar.gz)
